// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA_sM9Zh4kNUJbzftTTx19kUe8yDm6ZhI',
    appId: '1:163481399479:web:0c468d963b366ffaf3dd32',
    messagingSenderId: '163481399479',
    projectId: 'fasum-app-49dea',
    authDomain: 'fasum-app-49dea.firebaseapp.com',
    storageBucket: 'fasum-app-49dea.firebasestorage.app',
    measurementId: 'G-NTGCGHWD31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5xrliqfdMT-Vgsh1UjDFE0aci3YC9Gz8',
    appId: '1:163481399479:android:69bc86415df88cacf3dd32',
    messagingSenderId: '163481399479',
    projectId: 'fasum-app-49dea',
    storageBucket: 'fasum-app-49dea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGFhzC9Xu5egxLFnVIEO1ipXpzP2lr1Zk',
    appId: '1:163481399479:ios:f9628226e5ae63c4f3dd32',
    messagingSenderId: '163481399479',
    projectId: 'fasum-app-49dea',
    storageBucket: 'fasum-app-49dea.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGFhzC9Xu5egxLFnVIEO1ipXpzP2lr1Zk',
    appId: '1:163481399479:ios:f9628226e5ae63c4f3dd32',
    messagingSenderId: '163481399479',
    projectId: 'fasum-app-49dea',
    storageBucket: 'fasum-app-49dea.firebasestorage.app',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA_sM9Zh4kNUJbzftTTx19kUe8yDm6ZhI',
    appId: '1:163481399479:web:01175a4dfc37648bf3dd32',
    messagingSenderId: '163481399479',
    projectId: 'fasum-app-49dea',
    authDomain: 'fasum-app-49dea.firebaseapp.com',
    storageBucket: 'fasum-app-49dea.firebasestorage.app',
    measurementId: 'G-2J8G3PSP7W',
  );

}